echo -e "\033[0;35m"
echo "//==========================================================================\\"
echo "||COIN HUNTERS NODE                                                           ||"
echo "||👑 Crypto Community & Validator Service & Startup Acc.Web3 DeFi Blockchain Tech Investor, Researcher and Content Creator ||"
echo "\\==========================================================================//"
echo -e "\e[0m"
